Traceback (most recent call last):
  File "debug_traceback_example.py", line 4, in <module>
    raise Exception('This is a message error.')
Exception: This is a message error.
